### ISSUE TITLE
Vec2Dクラスのdot/crossの精度問題

### ISSUE THREAD

**Issue by yumetodo** [Siv3D/siv8#1]
**追加する機能の内容 | Describe the solution you'd like**

```cpp
namespace s3d
{
	template <class Type> struct Vector2D;
	using Float2	= Vector2D<float>;
	using Vec2		= Vector2D<double>;
}

	template <class Type>
	inline constexpr typename Vector2D<Type>::value_type Vector2D<Type>::dot(const Vector2D v) const noexcept
	{
		return x * v.x + y * v.y;
	}

	template <class Type>
	inline constexpr typename Vector2D<Type>::value_type Vector2D<Type>::cross(const Vector2D v) const noexcept
	{
		return x * v.y - y * v.x;
	}
```

v0.6のdot/crossの実装では、value_typeに丸められる仕様になっている。すると以下のような結果を得る

```cpp
Vec2D v1;
Fload2D f1;

f1.dot(v1) ;// => 戻り値の型はdoubleではなくfloat
```

C++として考えたとき、floatはdoubleに昇格されるので[[conv.fpprom]](https://timsong-cpp.github.io/cppwp/n4861/conv.fpprom#def:floating-point_promotion)、この戻り値の型もdoubleであるべきかに思える

一方で数学的に考えたとき、有効桁数の問題からfloatとdoubleではfloatのほうが精度が低いのでfloatのままでいいとも考えられる。

いずれにせよ、v0.6系では`Vector2D<T>`と`Vector2D<U>`のdot/crossメンバ関数が定義されてなかったので、型変換コンストラクタを間に挟むわかりくい実装となっていたことがこの問題を潜在的なものにしていたと考えられうる

- dot/crossの精度問題について結論をだす
- Vector2D<T>`と`Vector2D<U>`のdot/crossメンバ関数が定義される

**その機能の追加によって解決する問題 | Is your feature request related to a problem? Please describe.**

- 型を意識せずに内積/外積が計算できる
- https://github.com/Siv3D/OpenSiv3D/issues/848 のような実装を容易にする

**備考 | Additional context**

- ref: https://gist.github.com/Reputeless/3ae414cace581526bf7771745aad181b

**Comment by yumetodo** [comment]
<details>
<summary>Discordでのやり取り抜粋</summary>
yumetodo
 — 
今日 00:14

        [[nodiscard]]
        constexpr auto operator()(const Vec2 v1, const Float2 v2) const noexcept
        {
            return Vec2{ v1 }.dot(v2);
        }



これってもしかしてFloat2にdotってメンバ関数いないって話・・・？
Reputeless
 — 
今日 00:14
f1.dot(v1) すると戻り値が double であるべきだけど float になる問題があって、そのワークアラウンドです。
いずれにせよ内部計算で float と double 強いほうの型に合わせて計算するので、余計なコストは発生していません。これが最適な実装です。

Reputeless
 — 
今日 00:19
まぁ先に Float2::dot() を修正すべきかもしれません。
yumetodo
 — 
今日 00:20

constexpr value_type dot(Vector2D v) const noexcept;



というか Vector2D<T> と Vector2D<U>のdot定義されてないのか

Reputeless
 — 
今日 00:24
dot() 以外も FLoat2 のメンバ関数でそういう精度混合関連の問題残ってるので、このあたりの抜本的修正は v0.8 で。Float2, Vec2 は重要クラスなので、v0.6.x であまり手を入れたくないです。
yumetodo
 — 
今日 00:26
Vector2D<T>のTってfloat/double以外想定していない・・・？
Reputeless
 — 
今日 00:26
はい

Reputeless
 — 
今日 00:35
ま、でも s3d::Math::Xxx でオーバーロード提供、s3d::Xxx は丸投げ、は現行のスタイルなので、ひとまず今回はそれに合わせます。
Math.hpp / Math.ipp / Math_Functors.ipp の抜本的な設計改良については、v0.8 に向けて再検討します。

yumetodo
 — 
今日 00:43
・・・うーん？
ちょっとまって
そもそも float * doubleの結果、本当にdoubleになるべきなのか・・・？ベクトル計算において
有効桁数どうなってるんだこれ
</details>

**Comment by Reputeless** [comment]
情報（精度）が欠落すると困るので、精度を縮小するような計算はしません。
Siv3D の目指す挙動は HLSL や GLSL などのシェーダ言語とも一貫しています。

**Comment by Reputeless** [comment]
開発中の Siv3D v0.8 にて、`Float2` dot `Vec2` の結果が `Vec2` になるよう修正しました。
ご報告ありがとうございました。
