### ISSUE TITLE
`SIV3D_INTRINSIC_TYPE` が定義されない可能性がある

### ISSUE THREAD

**Issue by yaito3014** [Siv3D/siv8#12]
https://github.com/Siv3D/siv8/blob/3268de70c7444325564cf911bba138e30057cacb/Siv3D/include/Siv3D/Platform.hpp#L153-L165 の拡張命令セットのチェックにおいていずれにも該当しなかった場合には `SIV3D_INTRINSIC_TYPE` が定義されず、 https://github.com/Siv3D/siv8/blob/3268de70c7444325564cf911bba138e30057cacb/Test/Test_Platform.cpp#L18 のような文字列の結合を意図したコードでエラーが発生してしまいます

他のチェックと同様に `#error` を利用して早期にエラーを報告するか、該当するものがない場合にもマクロ自体は提供するべきだと思われます

**Comment by Reputeless** [comment]
ご報告ありがとうございました。`#error` になるよう修正しました。
