### ISSUE TITLE
Array 関連のテンプレートパラメータ制約の問題

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/siv8#6]
1. （質問）コンセプト `HasAsArray` が `typename Type::value_type` を要求していますが、意図したものですか？　代わりに `.asArray()` の戻り値 `R` に `typename R::value_type` と  `typename R::allocator_type` を要求するべきだと思います。
2. コンセプト `HasAsArray` が常に lvalue に対する `.asArray()` の呼び出しを要求していますが、完全転送して呼び出せることを要求するべきです。
3. （質問）`Array::Array(size_type size, Arg::generator_<Fty> generator)` などのテンプレートパラメータ制約で、ジェネレータの戻り値が要素の型と**完全に一致**することを要求していますが、それでは不便だと思います。「要素の型に**変換可能**」に制約を緩めたほうが良いと思いますが、どうでしょうか？
4. `.all()` と `.any()` について、`std::predicate<Fty, value_type>` の制約がありますが、これでは右辺値参照を受け取るような関数（オブジェクト）が制約を満たしてしまいます。右辺値参照を受け取るような関数が渡されたところで適用はできないので、エラーが出ることには変わりませんが、この場合は標準ライブラリのヘッダからエラーが出るので、わかりにくいものとなります。`std::predicate<Fty, const value_type&>` にするべきです。

```c++
# include <Siv3D.hpp>

struct Test
{
    // using value_type = int32;  // 1.

    Array<int32> asArray() &&  // 2.
    {
        return {};
    }
};

void Main()
{
    const Array a(Test{});  // 1. 2.
    const Array<int64> b(10, Arg::generator = [x = 0]() mutable { return x++; });  // 3.

    // b.all([](int32&& x) { return x == 0; });  // 4.
}
```

**1. 2. の変更例**

```c++
// Siv3D/Array.hpp
namespace s3d
{
	template <class Type>
	concept ArrayLike = requires(Type&& t)
	{
		Array<typename std::remove_cvref_t<Type>::value_type, typename std::remove_cvref_t<Type>::allocator_type>{ std::forward<Type>(t) };
	};

	template <class Type>
	concept HasAsArray = requires(Type&& t)
	{
		{ std::forward<Type>(t).asArray() } -> ArrayLike;
	};
}
```

**Comment by Reputeless** [comment]
たいへん解像度が高い指摘です！ 開発に反映させたいと思います。
お手数でなければ、気軽に個別に PR を送ってコミット実績に残してください。
既存コードでできないこと、新コードでできることの比較コードが付属していれば迅速にマージできます。

**Comment by Reputeless** [comment]
1 → そうしましょう。
3 → 緩和したいと思います。

**Comment by Raclamusi** [comment]
> お手数でなければ、気軽に個別に PR を送ってコミット実績に残してください。

もしかして、この「個別に」は「それぞれの変更を別々に」という意図でしたか？

**Comment by Reputeless** [comment]
すみません。ここ数日忙しくて PR への反応ができていませんでした。そうですね。個別のほうが採用非採用を選べるので個人的には嬉しいです。現在の PR #7 については追って確認します。

**Comment by Reputeless** [comment]
fixed in #7
